lang: python
notifications:
  email:
    on_success: never
    on_failure: always
sudo: required
services:
  - docker
before_install:
- gem install travis
- wget -O /tmp/fedora-22-64.tar.xz https://download.fedoraproject.org/pub/fedora/linux/releases/22/Docker/x86_64/Fedora-Docker-Base-22-20150521.x86_64.tar.xz
- docker load -i /tmp/fedora-22-64.tar.xz
before_script:
- docker run -i --privileged -d -v $HOME/build/$TRAVIS_REPO_SLUG:/home/travis --name test_fedora Fedora-Docker-Base-22-20150521.x86_64 bash
- docker exec -i test_fedora bash -c "useradd -g root fedora"
script:
- ruby rel-eng/travis/set-variables.rb
- rel-eng/travis/build.sh
