lang: python
branches:
  only:
  - master
notifications:
  email:
    on_success: never
    on_failure: always
sudo: required
before_install:
- echo "deb http://us.archive.ubuntu.com/ubuntu trusty main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update
- wget https://github.com/dgoodwin/tito/archive/tito-0.4.18-1.tar.gz -O /tmp/tito.tar.gz
- git clone https://git.fedorahosted.org/git/copr.git /tmp/copr
install:
- sudo apt-get install mock pigz python-lzma
- sudo pip install flake8 flake8-diff
- sudo pip install /tmp/tito.tar.gz
- cd /tmp/copr/python
- sudo pip install -r requirements.txt
- sudo python setup.py install
- sudo groupadd mock
- sudo usermod -a -G mock travis
- cd $HOME/build/$TRAVIS_REPO_SLUG
before_script:
- sudo cp rel-eng/travis/mock/rpg.cfg /etc/mock/
- git config user.email "travis@localhost" && git config user.name "Travis"
script: rel-eng/travis/build.sh
after_success: rel-eng/travis/upload.sh
